
# dataset choise
dataset: 'malaga' # kitti, malaga or parking


# find new candidates method
find_new_candidates_method: 'sift-sift' # 'shi-mask', 'sift-mask' or 'sift-sift'

# initialization parameters
init_detector: 'sift'
init_descriptor: 'sift'

# debug
debug: False

# visualization
visualization: True
animation: True

# parameters
sift_alpha: 1 # 1 works well with KITTI and Parking
shi_alpha: 1.5 # 1.5 worked well with KITTI 

sift_ransac_confidence: 0.99999
shi_ransac_confidence: 0.999993 # 0.999993 worked well with KITTI (but no inliers around 600)


# parameters for locally consistent sift-sift:
# sift_alpha: 1
# sift_ransac_confidence: 0.99999


